### ISSUE TITLE
Enforce a minimum validity time?

### ISSUE THREAD

**Issue by tfpauly** [chris-wood/draft-group-privacypass-k-check#1]
If the resource can get refreshed very frequently (like every second), a client could still be targeted without detecting an attack. One solution is to have a minimum time for validity.

**Comment by tfpauly** [comment]
You could also have the mirror police the keys being distributed to make sure that key rotations seem reasonable, and there's not a flipping between keys that could look like targeting.

**Comment by chris-wood** [comment]
[From @dvorak42](https://github.com/chris-wood/draft-group-privacypass-k-check/pull/2#discussion_r1245310746).

**Comment by chris-wood** [comment]
#2 includes a minimum validity time as a mirror configuration parameter.

**Comment by chris-wood** [comment]
Closing as resolved by #2.

**Comment by bemasc** [comment]
I think this needs some more motivation.  If clients only initiate sessions using currently-fresh resources, then short validity windows do not provide any ability to target individual clients (ignoring clock skew).

I would like to see some more specific rationale for this recommendation, if it is necessary at all.
