### ISSUE TITLE
Recommend K=1 for certain use cases

### ISSUE THREAD

**Issue by bemasc** [chris-wood/draft-group-privacypass-k-check#16]
The K-Check protocol is described as an abstract, general-purpose consistency protocol, and in that context it makes sense for K to be a free parameter.  However, in specific use cases there may be particular values of K that make sense.  If the client's privacy protection is already subject to a Single Point of Failure, then the optimal value for K is 1, i.e. a mirror operated by the SPOF.

For example, in OHTTP, increasing K does not provide increased privacy protection, because a malicious Relay can break the privacy guarantee even if consistency is preserved.  Increasing K can even reduce privacy protection (see #14, #15).

Accordingly, the draft should note some cases where K=1 is recommended.

**Comment by chris-wood** [comment]
I understand the motivation for this, but I'm not confident we can make generally applicable recommendations. At best, it seems like we might be able to provide examples where certain values of K = 1. OHTTP is an obvious case for that. Would that work?

Separately, to make sure we're on the same page, does this issue assume that K is chosen for privacy reasons?

**Comment by bemasc** [comment]
I do think there is a generally applicable recommendation here.  I've written it up in #17.
